#server.port=80
#server.port.a=true
#server.port.b=true

server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/C76-S3-Ply-favorite
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      prefix: WEB-INF/page/
#      suffix: .jsp
   
mybatis:
  #实体类的路径
  type-aliases-package: com.yc.C76S3PlySpringBoot.bean
  configuration:
     map-underscore-to-camel-case: true
  
# 日志配置
logging:
  level:
    com:
      yc:
        C76S3PlySpringBoot:
          dao: debug
          web: warn
  
  

